package de.gaiasoft.osm.taglib.def;

import de.gaiasoft.osm.taglib.base.ValueBase;

public enum Value_LEISURE implements ValueBase {
    DANCING("dancing"),
    TRAMPOLINE_PARK("trampoline_park"),
    SUMMER_CAMP("summer_camp"),
    GAMBLING("gambling"),
    CASINO("casino"),
    ARENA("arena"),
    BATHING_PLACE("bathing_place"),
    BLEACHERS("bleachers"),
    MAZE("maze"),
    SAILING_CLUB("sailing_club"),
    ESCAPE_GAME("escape_game"),
    HACKERSPACE("hackerspace"),
    SOCCER_GOLF("soccer_golf"),
    BEACH_RESORT("beach_resort"),
    SHOOTING_GROUND("shooting_ground"),
    CLUB("club"),
    TABLE_TENNIS_TABLE("table_tennis_table"),
    STADIUM("stadium"),
    PITCH("pitch"),
    SLIPWAY("slipway"),
    LANDSCAPE_RESERVE("landscape_reserve"),
    PICNIC_SITE("picnic_site"),
    RESORT("resort"),
    DANCE("dance"),
    SWIMMING_POOL("swimming_pool"),
    SOCIAL_CLUB("social_club"),
    SPORTS_CENTRE("sports_centre"),
    HOT_SPRING("hot_spring"),
    PICNIC("picnic"),
    SKI_PLAYGROUND("ski_playground"),
    BIRD_HIDE("bird_hide"),
    BBQ("bbq"),
    WILDLIFE_HIDE("wildlife_hide"),
    FOOT_BATH("foot_bath"),
    MARINA("marina"),
    SPORTS_HALL("sports_hall"),
    SWIMMING_AREA("swimming_area"),
    DISC_GOLF_COURSE("disc_golf_course"),
    PADDLING_POOL("paddling_pool"),
    VIDEO_ARCADE("video_arcade"),
    NATURE_RESERVE("nature_reserve"),
    ADULT_GAMING_CENTRE("adult_gaming_centre"),
    GOLF_COURSE("golf_course"),
    BOWLING_ALLEY("bowling_alley"),
    ICE_RINK("ice_rink"),
    TANNING_SALON("tanning_salon"),
    COMMON("common"),
    FITNESS_STATION("fitness_station"),
    SAUNA("sauna"),
    PLAYGROUND("playground"),
    HORSE_RIDING("horse_riding"),
    OUTDOOR_SEATING("outdoor_seating"),
    HOSPITAL("hospital"),
    TRACK("track"),
    PARK("park"),
    BANDSTAND("bandstand"),
    AMUSEMENT_ARCADE("amusement_arcade"),
    FISHING("fishing"),
    PICNIC_TABLE("picnic_table"),
    TURKISH_BATH("turkish_bath"),
    FITNESS_CENTRE("fitness_centre"),
    FISH_SPA("fish_spa"),
    WATER_PARK("water_park"),
    DOG_PARK("dog_park"),
    BEACH("beach"),
    RECREATION_GROUND("recreation_ground"),
    SCHOOLYARD("schoolyard"),
    GARDEN("garden"),
    MINIATURE_GOLF("miniature_golf"),
    FIREPIT("firepit"),
    RED_LIGHT_DISTRICT("red_light_district"),
    ;

    private String value;
    Value_LEISURE(String value) {
        this.value = value;
    }

    @Override
    public String getValue() { return value; }
}
