package de.gaiasoft.osm.taglib.def;

import de.gaiasoft.osm.taglib.base.ValueBase;

public enum Value_NATURAL implements ValueBase {
    BREAKER("breaker"),
    SADDLE("saddle"),
    BARE_ROCK("bare_rock"),
    BLOWHOLE("blowhole"),
    MORAINE("moraine"),
    RIVERBANK("riverbank"),
    SINKHOLE("sinkhole"),
    LANDFORM("landform"),
    SHRUB("shrub"),
    CLOUD("cloud"),
    HEATH("heath"),
    SPRING("spring"),
    ATOLL("atoll"),
    BIRDS_NEST("birds_nest"),
    AVALANCHE_DAM("avalanche_dam"),
    LIANA("liana"),
    GEOTHERMAL("geothermal"),
    WOOD("wood"),
    BAY("bay"),
    TREE_ROW("tree_row"),
    MARSH("marsh"),
    REEF("reef"),
    RIVERBED("riverbed"),
    COASTLINE("coastline"),
    CAVE("cave"),
    WETLAND("wetland"),
    DUNE("dune"),
    HOT_SPRING("hot_spring"),
    TREE("tree"),
    WALLOW("wallow"),
    BUTTE("butte"),
    GULLY("gully"),
    SCRUB("scrub"),
    ANTHILL("anthill"),
    WATER("water"),
    GEYSER("geyser"),
    STRAIT("strait"),
    ESKER("esker"),
    MOSS("moss"),
    SAND("sand"),
    MOOR("moor"),
    GORGE("gorge"),
    PLANT("plant"),
    VALLEY("valley"),
    LAKE("lake"),
    MUD("mud"),
    SCREE("scree"),
    NALED("naled"),
    CREVASSE("crevasse"),
    GEOTHERMAL_FIELD("geothermal_field"),
    CLIFF("cliff"),
    GEOTHERMAL_AREA("geothermal_area"),
    CAVE_ENTRANCE("cave_entrance"),
    ARETE("arete"),
    MOUNTAIN_RANGE("mountain_range"),
    FELL("fell"),
    PALAEONTOLOGICAL_SITE("palaeontological_site"),
    ROCK("rock"),
    FJORD("fjord"),
    ISTHMUS("isthmus"),
    LAVA("lava"),
    BEDROCK("bedrock"),
    ROCKS("rocks"),
    MESA("mesa"),
    GRASS("grass"),
    PLATEAU("plateau"),
    LAND("land"),
    VOLCANO("volcano"),
    RIDGE("ridge"),
    GLACIER("glacier"),
    HERB("herb"),
    MEADOW("meadow"),
    SHOAL("shoal"),
    TREE_STUMP("tree_stump"),
    TERMITE_MOUND("termite_mound"),
    TIDAL("tidal"),
    CRATER("crater"),
    PEAK("peak"),
    LANDSLIDE("landslide"),
    GRASSLAND("grassland"),
    STONE("stone"),
    EARTH_BANK("earth_bank"),
    PENINSULA("peninsula"),
    TUNDRA("tundra"),
    HILL("hill"),
    TREE_GROUP("tree_group"),
    RIVER_TERRACE("river_terrace"),
    BEACH("beach"),
    SHINGLE("shingle"),
    DESERT("desert"),
    CAPE("cape"),
    ;

    private String value;
    Value_NATURAL(String value) {
        this.value = value;
    }

    @Override
    public String getValue() { return value; }
}
