package de.gaiasoft.osm.taglib.def;

import de.gaiasoft.osm.taglib.base.ValueBase;

public enum Value_CRAFT implements ValueBase {
    HVAC("hvac"),
    ELECTRICIAN("electrician"),
    PHOTOGRAPHIC_LABORATORY("photographic_laboratory"),
    SAILMAKER("sailmaker"),
    GRINDING_MILL("grinding_mill"),
    ATELIER("atelier"),
    CARPENTER("carpenter"),
    ENGRAVER("engraver"),
    CAR_REPAIR("car_repair"),
    BOOKBINDER("bookbinder"),
    LOCKSMITH("locksmith"),
    TILER("tiler"),
    BLACKSMITH("blacksmith"),
    JEWELLER("jeweller"),
    STAND_BUILDER("stand_builder"),
    ORGAN_BUILDER("organ_builder"),
    PAPERHANGER("paperhanger"),
    WINERY("winery"),
    WATCHMAKER("watchmaker"),
    RESTORATION("restoration"),
    CABINET_MAKER("cabinet_maker"),
    METAL_CONSTRUCTION("metal_construction"),
    WELDER("welder"),
    LUTHIER("luthier"),
    OIL_MILL("oil_mill"),
    BAKERY("bakery"),
    CHIMNEY_SWEEPER("chimney_sweeper"),
    WINDOW_CONSTRUCTION("window_construction"),
    PRINTER("printer"),
    SADDLER("saddler"),
    ELECTRICAN("electrican"),
    SHOEMAKER("shoemaker"),
    GARDENER("gardener"),
    LEATHER("leather"),
    STONEMASON("stonemason"),
    INSULATION("insulation"),
    PAINTER("painter"),
    UPHOLSTRER("upholstrer"),
    SCULPTOR("sculptor"),
    PRINTMAKER("printmaker"),
    SAWMILL("sawmill"),
    CARPET_LAYER("carpet_layer"),
    TINSMITH("tinsmith"),
    DRESSMAKER("dressmaker"),
    SIGNMAKER("signmaker"),
    BASKET_MAKER("basket_maker"),
    UPHOLSTERER("upholsterer"),
    CLOCKMAKER("clockmaker"),
    BAG_REPAIR("bag_repair"),
    DISTILLERY("distillery"),
    RIGGER("rigger"),
    AGRICULTURAL_ENGINES("agricultural_engines"),
    BOATBUILDER("boatbuilder"),
    EMBROIDERER("embroiderer"),
    BEEKEEPER("beekeeper"),
    TAILOR("tailor"),
    PAVER("paver"),
    CONFECTIONERY("confectionery"),
    HANDICRAFT("handicraft"),
    CATERER("caterer"),
    INFORMATION_ELECTRONICS("information_electronics"),
    MINT("mint"),
    PLUMBER("plumber"),
    PARQUET_LAYER("parquet_layer"),
    BREWERY("brewery"),
    BUILDER("builder"),
    KEY_CUTTER("key_cutter"),
    ROOFER("roofer"),
    SEWING("sewing"),
    MUSICAL_INSTRUMENT("musical_instrument"),
    PHOTOGRAPHER("photographer"),
    GOLDSMITH("goldsmith"),
    PLASTERER("plasterer"),
    TOOLMAKER("toolmaker"),
    SWEEP("sweep"),
    LACQUERER("lacquerer"),
    PIANO_TUNER("piano_tuner"),
    DENTAL_TECHNICIAN("dental_technician"),
    SUN_PROTECTION("sun_protection"),
    GLAZIERY("glaziery"),
    OPTICIAN("optician"),
    ELECTRONICS_REPAIR("electronics_repair"),
    FLOORER("floorer"),
    POTTERY("pottery"),
    TURNER("turner"),
    JOINER("joiner"),
    COOPER("cooper"),
    SCAFFOLDER("scaffolder"),
    ;

    private String value;
    Value_CRAFT(String value) {
        this.value = value;
    }

    @Override
    public String getValue() { return value; }
}
