package de.gaiasoft.osm.taglib.def;

import de.gaiasoft.osm.taglib.base.ValueBase;

public enum Value_BUILDING implements ValueBase {
    COLLEGE("college"),
    CONTAINER("container"),
    PARKING("parking"),
    SHED("shed"),
    COMMERCIAL("commercial"),
    HUT("hut"),
    CONDOMINIUM("condominium"),
    COWSHED("cowshed"),
    OFFICE("office"),
    BOATHOUSE("boathouse"),
    BARN("barn"),
    SCHOOL("school"),
    PAVILION("pavilion"),
    FARM("farm"),
    STADIUM("stadium"),
    GROUND_STATION("ground_station"),
    ENTRANCE("entrance"),
    DIGESTER("digester"),
    REMOTE_DIGITAL_TERMINAL("remote_digital_terminal"),
    STILT_HOUSE("stilt_house"),
    HANGAR("hangar"),
    BUNKER("bunker"),
    CONSERVATORY("conservatory"),
    SPORTS_CENTRE("sports_centre"),
    SEMIDETACHED_HOUSE("semidetached_house"),
    TECH_CAB("tech_cab"),
    GREENHOUSE("greenhouse"),
    SYNAGOGUE("synagogue"),
    DATA_CENTER("data_center"),
    MARQUEE("marquee"),
    RIDING_HALL("riding_hall"),
    CHAPEL("chapel"),
    WAREHOUSE("warehouse"),
    FARM_AUXILIARY("farm_auxiliary"),
    SHRINE("shrine"),
    DETACHED("detached"),
    GARAGES("garages"),
    EXIT("exit"),
    MANUFACTURE("manufacture"),
    TOILETS("toilets"),
    SPORTS_HALL("sports_hall"),
    PROPOSED("proposed"),
    RUINS("ruins"),
    TRULLO("trullo"),
    STY("sty"),
    BRIDGE("bridge"),
    GRANDSTAND("grandstand"),
    APARTMENTS("apartments"),
    STATIC_CARAVAN("static_caravan"),
    RELIGIOUS("religious"),
    TENT("tent"),
    KINDERGARTEN("kindergarten"),
    MOSQUE("mosque"),
    ALLOTMENT_HOUSE("allotment_house"),
    HOUSEBOAT("houseboat"),
    UNIVERSITY("university"),
    CHURCH("church"),
    DORMITORY("dormitory"),
    CABIN("cabin"),
    PLANNED("planned"),
    HOUSE("house"),
    BARRACK("barrack"),
    CIVIC("civic"),
    RETAIL("retail"),
    SUPERMARKET("supermarket"),
    GOVERNMENT("government"),
    PUBLIC("public"),
    WATER_TOWER("water_tower"),
    GER("ger"),
    BREWERY("brewery"),
    TRAIN_STATION("train_station"),
    CONSTRUCTION("construction"),
    HOTEL("hotel"),
    SLURRY_TANK("slurry_tank"),
    TERRACE("terrace"),
    SEMI("semi"),
    HOSPITAL("hospital"),
    CATHEDRAL("cathedral"),
    CARPORT("carport"),
    BAKEHOUSE("bakehouse"),
    ROOF("roof"),
    BUNGALOW("bungalow"),
    YES("yes"),
    GARAGE("garage"),
    TRANSPORTATION("transportation"),
    TRANSFORMER_TOWER("transformer_tower"),
    INDUSTRIAL("industrial"),
    CENTRAL_OFFICE("central_office"),
    RESIDENTIAL("residential"),
    SERVICE("service"),
    STABLE("stable"),
    TEMPLE("temple"),
    KIOSK("kiosk"),
    FONT("font"),
    ;

    private String value;
    Value_BUILDING(String value) {
        this.value = value;
    }

    @Override
    public String getValue() { return value; }
}
