package de.gaiasoft.osm.taglib.def;

import de.gaiasoft.osm.taglib.base.ValueBase;

public enum Value_HIGHWAY implements ValueBase {
    CONVEYOR("conveyor"),
    DOOR("door"),
    CORRIDOR("corridor"),
    MINOR("minor"),
    PRIMARY_LINK("primary_link"),
    RURAL("rural"),
    FORD("ford"),
    REST_AREA("rest_area"),
    PATH("path"),
    TRAIL("trail"),
    ELEVATOR("elevator"),
    ROAD("road"),
    CATTLE_GRID("cattle_grid"),
    INCLINE("incline"),
    ABANDONED("abandoned"),
    STREET_LAMP("street_lamp"),
    BAZAAR("bazaar"),
    TERTIARY_LINK("tertiary_link"),
    BYWAY("byway"),
    VIA_FERRATA("via_ferrata"),
    TERTIARY("tertiary"),
    SPEED_CAMERA("speed_camera"),
    LIVING_STREET("living_street"),
    STILE("stile"),
    MOTORWAY_LINK("motorway_link"),
    PRIORITY("priority"),
    TRUNK("trunk"),
    CROSSING("crossing"),
    MOTORWAY("motorway"),
    STEPS("steps"),
    RESIDENTIAL_LINK("residential_link"),
    SECONDARY("secondary"),
    TRAILHEAD("trailhead"),
    PASSING_PLACE("passing_place"),
    MOTORWAY_JUNCTION("motorway_junction"),
    PROPOSED("proposed"),
    STOP("stop"),
    TURNING_CIRCLE("turning_circle"),
    KERB("kerb"),
    FOOTWAY("footway"),
    EMERGENCY_BAY("emergency_bay"),
    CYCLEWAY("cycleway"),
    TRUNK_LINK("trunk_link"),
    PRIMARY("primary"),
    NO("no"),
    UNCLASSIFIED("unclassified"),
    ACCESS("access"),
    TURNING_LOOP("turning_loop"),
    TRUNK_JUNCTION("trunk_junction"),
    TRAFFIC_SIGN("traffic_sign"),
    BUS_GUIDEWAY("bus_guideway"),
    PLANNED("planned"),
    PLATFORM("platform"),
    UNKNOWN("unknown"),
    MOVING_WALKWAY("moving_walkway"),
    PISTE("piste"),
    RACEWAY("raceway"),
    STREET_LIGHT("street_light"),
    TRAFFIC_SIGNALS("traffic_signals"),
    YIELD("yield"),
    CONSTRUCTION("construction"),
    SECONDARY_LINK("secondary_link"),
    TRACK("track"),
    TRAFFIC_MIRROR("traffic_mirror"),
    UNSURFACED("unsurfaced"),
    ESCAPE("escape"),
    GIVE_WAY("give_way"),
    LANE("lane"),
    NOEXIT("noexit"),
    EMERGENCY_ACCESS_POINT("emergency_access_point"),
    BRIDLEWAY("bridleway"),
    YES("yes"),
    MINI_ROUNDABOUT("mini_roundabout"),
    SERVICES("services"),
    DISUSED("disused"),
    INCLINE_STEEP("incline_steep"),
    CYCLEWAY_LINK("cycleway_link"),
    SPEED_DISPLAY("speed_display"),
    RESIDENTIAL("residential"),
    MILESTONE("milestone"),
    SERVICE("service"),
    SKYWAY("skyway"),
    TRAFFIC_CALMING("traffic_calming"),
    PEDESTRIAN("pedestrian"),
    TOLL_BOOTH("toll_booth"),
    BUS_STOP("bus_stop"),
    GATE("gate"),
    GREEN_LANE("green_lane"),
    RAZED("razed"),
    TOLL_GANTRY("toll_gantry"),
    ;

    private String value;
    Value_HIGHWAY(String value) {
        this.value = value;
    }

    @Override
    public String getValue() { return value; }
}
