package de.gaiasoft.osm.taglib;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

import static de.gaiasoft.osm.taglib.TagValue.*;

public class TagKeyKnownValueMap extends HashMap<TagKey, Set<TagValue>> {
    private static TagKeyKnownValueMap instance = new TagKeyKnownValueMap();

    public static TagKeyKnownValueMap instance() {
        return instance;
    }

    public boolean isValueOk(TagKey key, TagValue value) {
        return get(key).contains(value);
    }

    private TagKeyKnownValueMap() {
        defineKnownValues(TagKey.PARKING, new TagValue[] {
                MULTI_STOREY,
                UNDERGROUND
        });
        defineKnownValues(TagKey.SITE_TYPE, new TagValue[] {
                MEGALITH,
                ROMAN_CIRCUS,
                TUMULUS,
                ROMAN_VILLA,
                PETROGLYPH,
                HUT_CIRCLE,
                BIGSTONE,
                FORTIFICATION,
                NECROPOLIS,
                SETTLEMENT
        });
        defineKnownValues(TagKey.BICYCLE, new TagValue[] {
                NO,
                DESIGNATED,
                YES,
                USE_SIDEPATH
        });
        defineKnownValues(TagKey.BIN, new TagValue[] {
                YES
        });
        defineKnownValues(TagKey.USAGE, new TagValue[] {
                INDUSTRIAL,
                IRRIGATION,
                TRANSMISSION,
                PENSTOCK,
                TAILRACE,
                TOURISM,
                MILITARY,
                HEADRACE
        });
        defineKnownValues(TagKey.MAXSPEED, new TagValue[] {
                SIGNALS,
                NONE,
                WALK
        });
        defineKnownValues(TagKey.LEAF_TYPE, new TagValue[] {
                BROADLEAVED,
                MIXED,
                LEAFLESS,
                NEEDLELEAVED
        });
        defineKnownValues(TagKey.ADVERTISING, new TagValue[] {
                COLUMN
        });
        defineKnownValues(TagKey.TYPE, new TagValue[] {
                BOUNDARY,
                MULTIPOLYGON,
                ROUTE,
                LAND_AREA
        });
        defineKnownValues(TagKey.GEOLOGICAL, new TagValue[] {
                PALAEONTOLOGICAL_SITE,
                OUTCROP,
                MORAINE
        });
        defineKnownValues(TagKey.BUILDING, new TagValue[] {
                CONTAINER,
                PARKING,
                SHED,
                COMMERCIAL,
                HUT,
                COWSHED,
                BOATHOUSE,
                BARN,
                SCHOOL,
                FARM,
                ENTRANCE,
                TECH_CAB,
                GREENHOUSE,
                SYNAGOGUE,
                MARQUEE,
                RIDING_HALL,
                CHAPEL,
                WAREHOUSE,
                SHRINE,
                DETACHED,
                GARAGES,
                SPORTS_HALL,
                RUINS,
                STY,
                GRANDSTAND,
                APARTMENTS,
                STATIC_CARAVAN,
                MOSQUE,
                HOUSEBOAT,
                UNIVERSITY,
                CHURCH,
                DORMITORY,
                HOUSE,
                CIVIC,
                RETAIL,
                PUBLIC,
                WATER_TOWER,
                TRAIN_STATION,
                HOTEL,
                SLURRY_TANK,
                TERRACE,
                HOSPITAL,
                CATHEDRAL,
                ROOF,
                BUNGALOW,
                YES,
                GARAGE,
                INDUSTRIAL,
                RESIDENTIAL,
                STABLE,
                TEMPLE,
                KIOSK
        });
        defineKnownValues(TagKey.DIPLOMATIC, new TagValue[] {
                AMBASSADORS_RESIDENCE,
                HIGH_COMMISSION,
                CONSULATE_GENERAL,
                HONORARY_CONSULATE,
                EMBASSY,
                DELEGATION,
                CONSULATE,
                PERMANENT_MISSION
        });
        defineKnownValues(TagKey.LEAF_CYCLE, new TagValue[] {
                DECIDUOUS,
                EVERGREEN
        });
        defineKnownValues(TagKey.DEFENSIVE, new TagValue[] {
                BERGFRIED,
                DONJON,
                KEEP
        });
        defineKnownValues(TagKey.RAILWAY, new TagValue[] {
                TRAM_STOP,
                YARD,
                BUFFER_STOP,
                TURNTABLE,
                LIGHT_RAIL,
                PLATFORM,
                SIGNAL_BOX,
                MONORAIL,
                SWITCH,
                FUNICULAR,
                WATER_TOWER,
                PRESERVED,
                STATION,
                CONSTRUCTION,
                ROUNDHOUSE,
                ABANDONED,
                TRAM,
                NARROW_GAUGE,
                SIGNAL,
                SUBWAY_ENTRANCE,
                TRAVERSER,
                RAIL,
                WASH,
                RAIL_BRAKE,
                DISUSED,
                CROSSING,
                HALT,
                LEVEL_CROSSING,
                SUBWAY,
                MILESTONE,
                STOP,
                MINIATURE,
                RAILWAY_CROSSING,
                DERAIL
        });
        defineKnownValues(TagKey.INCLINE, new TagValue[] {
                UP,
                DOWN
        });
        defineKnownValues(TagKey.DOCK, new TagValue[] {
                DRYDOCK,
                FLOATING
        });
        defineKnownValues(TagKey.ABANDONED, new TagValue[] {
                YES,
                VILLAGE
        });
        defineKnownValues(TagKey.SOCIAL_FACILITY, new TagValue[] {
                ASSISTED_LIVING,
                NURSING_HOME,
                DAY_CARE,
                AMBULATORY_CARE,
                GROUP_HOME,
                WORKSHOP,
                FOOD_BANK,
                HOSPICE,
                SOUP_KITCHEN
        });
        defineKnownValues(TagKey.SURFACE, new TagValue[] {
                PAVING_STONES,
                SAND,
                RED_SAND,
                GRASS,
                CONCRETE_LANES,
                ASPHALT,
                PAVED,
                UNPAVED
        });
        defineKnownValues(TagKey.NATURAL, new TagValue[] {
                SCREE,
                SADDLE,
                CLIFF,
                BARE_ROCK,
                CAVE_ENTRANCE,
                ARETE,
                SINKHOLE,
                SHRUB,
                FELL,
                HEATH,
                ROCK,
                SPRING,
                WOOD,
                BAY,
                VOLCANO,
                RIDGE,
                GLACIER,
                TREE_ROW,
                SHOAL,
                REEF,
                COASTLINE,
                WETLAND,
                HOT_SPRING,
                TREE,
                GULLY,
                TERMITE_MOUND,
                PEAK,
                SCRUB,
                ANTHILL,
                WATER,
                GEYSER,
                GRASSLAND,
                STRAIT,
                STONE,
                EARTH_BANK,
                SAND,
                TREE_GROUP,
                MOOR,
                BEACH,
                GORGE,
                SHINGLE,
                VALLEY,
                CAPE,
                MUD
        });
        defineKnownValues(TagKey.WIRES, new TagValue[] {
                DOUBLE
        });
        defineKnownValues(TagKey.HORSE, new TagValue[] {
                DESIGNATED
        });
        defineKnownValues(TagKey.SHELTER_TYPE, new TagValue[] {
                LEAN_TO,
                BASIC_HUT
        });
        defineKnownValues(TagKey.ROUTE, new TagValue[] {
                BUS,
                BICYCLE,
                NORDIC_WALKING,
                FITNESS_TRAIL,
                HIKING,
                LIGHT_RAIL,
                TROLLEYBUS,
                TRACKS,
                HORSE,
                PIPELINE,
                PISTE,
                RUNNING,
                SKI,
                SUBWAY,
                INLINE_SKATES,
                ROAD,
                FERRY,
                MTB,
                RAILWAY,
                TRAM,
                FOOT,
                TRAIN
        });
        defineKnownValues(TagKey.ANIMAL, new TagValue[] {
                SCHOOL,
                HORSE_WALKER
        });
        defineKnownValues(TagKey.PLACEMENT, new TagValue[] {
                TRANSITION
        });
        defineKnownValues(TagKey.BRIDGE, new TagValue[] {
                TRESTLE,
                CANTILEVER,
                VIADUCT,
                MOVABLE,
                AQUEDUCT,
                YES,
                COVERED,
                BOARDWALK
        });
        defineKnownValues(TagKey.ACCESS, new TagValue[] {
                DELIVERY,
                PRIVATE,
                DESIGNATED,
                DESTINATION
        });
        defineKnownValues(TagKey.AMENITY, new TagValue[] {
                COLLEGE,
                PARKING,
                STUDIO,
                FOUNTAIN,
                KNEIPP_WATER_CURE,
                PLACE_OF_WORSHIP,
                MUSIC_VENUE,
                ICE_CREAM,
                THEATRE,
                TROLLEY_BAY,
                MOTORCYCLE_PARKING,
                BANK,
                BAR,
                BOAT_RENTAL,
                HUNTING_STAND,
                COURTHOUSE,
                CUSTOMS,
                COMPRESSED_AIR,
                CINEMA,
                HOOKAH_LOUNGE,
                HOSPICE,
                COMMUNITY_CENTRE,
                PRISON,
                SOCIAL_FACILITY,
                ARTS_CENTRE,
                BUS_STATION,
                SKI_SCHOOL,
                TAXI,
                BUREAU_DE_CHANGE,
                WATERING_PLACE,
                WEIGHBRIDGE,
                BICYCLE_RENTAL,
                BBQ,
                BICYCLE_PARKING,
                DOCTORS,
                BOAT_STORAGE,
                PUBLIC_BOOKCASE,
                FAST_FOOD,
                SHOWER,
                SHELTER,
                GRIT_BIN,
                BROTHEL,
                PHOTO_BOOTH,
                MUSIC_SCHOOL,
                LANGUAGE_SCHOOL,
                LIBRARY,
                PLANETARIUM,
                DRIVING_SCHOOL,
                PRISON_CAMP,
                KITCHEN,
                CAR_WASH,
                REGISTER_OFFICE,
                RESTAURANT,
                POST_OFFICE,
                VETERINARY,
                BAKING_OVEN,
                MONASTERY,
                POLICE,
                FISH_SPA,
                GRAVE_YARD,
                RANGER_STATION,
                ANIMAL_BREEDING,
                STABLES,
                SANITARY_DUMP_STATION,
                DIVE_CENTRE,
                BABY_HATCH,
                FRIDGE,
                ADMINISTRATION,
                FUEL,
                CASINO,
                VEHICLE_INSPECTION,
                FIRE_HYDRANT,
                POST_BOX,
                SMOKING_AREA,
                SCHOOL,
                WATER_POINT,
                YOUTH_CENTRE,
                ATM,
                DANCING_SCHOOL,
                EXHIBITION_CENTRE,
                PUBLIC_BATH,
                NIGHTCLUB,
                NURSING_HOME,
                BIERGARTEN,
                BENCH,
                MARKETPLACE,
                MEDICAL_SUPPLY,
                ARCHIVE,
                TELEPHONE,
                CLOCK,
                TICKET_VALIDATOR,
                CHARGING_STATION,
                CONCERT_HALL,
                DENTIST,
                TOILETS,
                CAFE,
                FESTIVAL_GROUNDS,
                FERRY_TERMINAL,
                PHARMACY,
                CAR_RENTAL,
                EMBASSY,
                WASTE_DISPOSAL,
                BICYCLE_REPAIR_STATION,
                WASTE_BASKET,
                CONFERENCE_CENTRE,
                KINDERGARTEN,
                ANIMAL_BOARDING,
                INTERNET_CAFE,
                UNIVERSITY,
                CAR_SHARING,
                EMERGENCY_PHONE,
                HOSPITAL,
                ANIMAL_SHELTER,
                VENDING_MACHINE,
                TOWNHALL,
                PARKING_ENTRANCE,
                EVENTS_VENUE,
                RECYCLING,
                RETIREMENT_HOME,
                FIRE_STATION,
                RESEARCH_INSTITUTE,
                CREMATORIUM,
                WASTE_TRANSFER_STATION,
                DRINKING_WATER,
                PARKING_SPACE,
                CLINIC,
                PUB
        });
        defineKnownValues(TagKey.DENOTATION, new TagValue[] {
                NATURAL_MONUMENT
        });
        defineKnownValues(TagKey.MOUNTAIN_PASS, new TagValue[] {
                YES
        });
        defineKnownValues(TagKey.TOURISM, new TagValue[] {
                TRAIL_RIDING_STATION,
                GUEST_HOUSE,
                VIEWPOINT,
                HOSTEL,
                WINE_CELLAR,
                CHALET,
                ARTWORK,
                MOTEL,
                AQUARIUM,
                WILDERNESS_HUT,
                ATTRACTION,
                MUSEUM,
                ALPINE_HUT,
                CARAVAN_SITE,
                HOTEL,
                CAMP_SITE,
                INFORMATION,
                THEME_PARK,
                ZOO,
                PICNIC_SITE,
                APARTMENT,
                GALLERY
        });
        defineKnownValues(TagKey.TRAFFIC_SIGN, new TagValue[] {
                CITY_LIMIT
        });
        defineKnownValues(TagKey.LAND_AREA, new TagValue[] {
                ADMINISTRATIVE
        });
        defineKnownValues(TagKey.PUBLIC_TRANSPORT, new TagValue[] {
                STATION,
                STOP_AREA,
                STOP_POSITION,
                PLATFORM
        });
        defineKnownValues(TagKey.BUNKER_TYPE, new TagValue[] {
                HARDENED_AIRCRAFT_SHELTER,
                MUNITIONS,
                PILLBOX
        });
        defineKnownValues(TagKey.VEHICLE, new TagValue[] {
                DESTINATION
        });
        defineKnownValues(TagKey.HEALTHCARE, new TagValue[] {
                LABORATORY,
                BLOOD_DONATION
        });
        defineKnownValues(TagKey.GOLF, new TagValue[] {
                HOLE,
                BUNKER,
                DRIVING_RANGE,
                GREEN,
                ROUGH,
                PIN,
                FAIRWAY,
                TEE,
                WATER_HAZARD,
                LATERAL_WATER_HAZARD
        });
        defineKnownValues(TagKey.GOVERNMENT, new TagValue[] {
                REGISTER_OFFICE,
                YOUTH_WELFARE_DEPARTMENT,
                CUSTOMS,
                ARCHIVE,
                TAX,
                CADASTER,
                PROSECUTOR,
                MINISTRY,
                HEALTHCARE,
                STATISTICS
        });
        defineKnownValues(TagKey.PRISON_CAMP, new TagValue[] {
                CONCENTRATION_CAMP
        });
        defineKnownValues(TagKey.LANDUSE, new TagValue[] {
                POND,
                RELIGIOUS,
                COMMERCIAL,
                FOREST,
                DEPOT,
                FARMYARD,
                BROWNFIELD,
                PLANT_NURSERY,
                FARMLAND,
                RETAIL,
                LANDFILL,
                VINEYARD,
                GRASS,
                CONSTRUCTION,
                FARM,
                MILITARY,
                RAILWAY,
                CEMETERY,
                PASTURE,
                MEADOW,
                GREENHOUSE_HORTICULTURE,
                GREENFIELD,
                VILLAGE_GREEN,
                ALLOTMENTS,
                FLOWERBED,
                BASIN,
                SALT_POND,
                QUARRY,
                FARMYARDS,
                GARAGES,
                AQUACULTURE,
                INDUSTRIAL,
                RESIDENTIAL,
                ORCHARD,
                RECREATION_GROUND,
                RESERVOIR
        });
        defineKnownValues(TagKey.POWER, new TagValue[] {
                CABLE_DISTRIBUTION_CABINET,
                LINE,
                CONVERTER,
                TRANSFORMER,
                GENERATOR,
                HELIOSTAT,
                POLE,
                SUB_STATION,
                SWITCH,
                SWITCHGEAR,
                PLANT,
                SUBSTATION,
                STATION,
                PORTAL,
                CABLE,
                MINOR_LINE,
                TOWER
        });
        defineKnownValues(TagKey.PLACE, new TagValue[] {
                CONTINENT,
                COUNTRY,
                ISOLATED_DWELLING,
                TOWN,
                CITY,
                HAMLET,
                ISLAND,
                COUNTY,
                LOCALITY,
                ISLET,
                SQUARE,
                NEIGHBOURHOOD,
                ARCHIPELAGO,
                SUBURB,
                STATE,
                VILLAGE
        });
        defineKnownValues(TagKey.PUMP, new TagValue[] {
                POWERED,
                MANUAL
        });
        defineKnownValues(TagKey.LEISURE, new TagValue[] {
                BOWLING_ALLEY,
                ICE_RINK,
                TANNING_SALON,
                BEACH_RESORT,
                COMMON,
                FITNESS_STATION,
                SAUNA,
                TABLE_TENNIS_TABLE,
                PLAYGROUND,
                STADIUM,
                HORSE_RIDING,
                OUTDOOR_SEATING,
                PITCH,
                SLIPWAY,
                RESORT,
                TRACK,
                DANCE,
                PARK,
                SWIMMING_POOL,
                BANDSTAND,
                SPORTS_CENTRE,
                FISHING,
                HOT_SPRING,
                PICNIC_TABLE,
                BIRD_HIDE,
                WILDLIFE_HIDE,
                FOOT_BATH,
                MARINA,
                SPORTS_HALL,
                FITNESS_CENTRE,
                FISH_SPA,
                WATER_PARK,
                SWIMMING_AREA,
                DISC_GOLF_COURSE,
                DOG_PARK,
                GARDEN,
                MINIATURE_GOLF,
                NATURE_RESERVE,
                FIREPIT,
                ADULT_GAMING_CENTRE,
                GOLF_COURSE
        });
        defineKnownValues(TagKey.CEMETERY, new TagValue[] {
                GRAVE
        });
        defineKnownValues(TagKey.FOOT, new TagValue[] {
                NO,
                DESIGNATED,
                YES
        });
        defineKnownValues(TagKey.AERIALWAY, new TagValue[] {
                CABLE_CAR,
                PYLON,
                T_BAR,
                MAGIC_CARPET,
                DRAG_LIFT,
                STATION,
                GOODS,
                CHAIR_LIFT,
                GONDOLA
        });
        defineKnownValues(TagKey.ONEWAY, new TagValue[] {
                NO,
                _1,
                YES
        });
        defineKnownValues(TagKey.RELIGION, new TagValue[] {
                MUSLIM,
                HINDU,
                CHRISTIAN,
                BUDDHIST,
                JEWISH,
                SHINTO
        });
        defineKnownValues(TagKey.SMOOTHNESS, new TagValue[] {
                GOOD
        });
        defineKnownValues(TagKey.INFORMATION, new TagValue[] {
                TACTILE_MODEL,
                GUIDEPOST,
                TACTILE_MAP,
                OFFICE,
                TERMINAL,
                AUDIOGUIDE,
                MAP,
                BOARD
        });
        defineKnownValues(TagKey.JUNCTION, new TagValue[] {
                ROUNDABOUT
        });
        defineKnownValues(TagKey.MICROBREWERY, new TagValue[] {
                YES
        });
        defineKnownValues(TagKey.CRAFT, new TagValue[] {
                HVAC,
                ELECTRICIAN,
                CARPENTER,
                CAR_REPAIR,
                BOOKBINDER,
                TILER,
                BLACKSMITH,
                ORGAN_BUILDER,
                PAPERHANGER,
                WINERY,
                WATCHMAKER,
                METAL_CONSTRUCTION,
                CHIMNEY_SWEEPER,
                WINDOW_CONSTRUCTION,
                SADDLER,
                ELECTRICAN,
                SHOEMAKER,
                GARDENER,
                STONEMASON,
                PAINTER,
                SAWMILL,
                CARPET_LAYER,
                TINSMITH,
                DRESSMAKER,
                BASKET_MAKER,
                UPHOLSTERER,
                DISTILLERY,
                AGRICULTURAL_ENGINES,
                BOATBUILDER,
                BEEKEEPER,
                TAILOR,
                CONFECTIONERY,
                HANDICRAFT,
                CATERER,
                INFORMATION_ELECTRONICS,
                PLUMBER,
                PARQUET_LAYER,
                BUILDER,
                ROOFER,
                PHOTOGRAPHER,
                TOOLMAKER,
                DENTAL_TECHNICIAN,
                SUN_PROTECTION,
                GLAZIERY,
                OPTICIAN,
                FLOORER,
                POTTERY,
                TURNER,
                JOINER,
                COOPER,
                SCAFFOLDER
        });
        defineKnownValues(TagKey.EMERGENCY, new TagValue[] {
                ACCESS_POINT,
                AMBULANCE_STATION,
                AED,
                SIREN,
                YES,
                ASSEMBLY_POINT,
                SUCTION_POINT,
                EMERGENCY_WARD_ENTRANCE,
                LIFE_RING,
                LIFEGUARD_BASE,
                LIFEGUARD_TOWER,
                FIRE_HYDRANT,
                FIRST_AID_KIT,
                LIFEGUARD_PLACE,
                PHONE,
                MOUNTAIN_RESCUE,
                WATER_RESCUE_STATION,
                DEFIBRILLATOR,
                FIRE_WATER_POND,
                FIRST_AID
        });
        defineKnownValues(TagKey.RECYCLING_TYPE, new TagValue[] {
                CONTAINER
        });
        defineKnownValues(TagKey.TRACKTYPE, new TagValue[] {
                GRADE5,
                GRADE4,
                GRADE3,
                GRADE2,
                GRADE1
        });
        defineKnownValues(TagKey.SOURCE, new TagValue[] {
                YAHOO,
                YAHOO,
                HIRES_AERIAL_IMAGERY
        });
        defineKnownValues(TagKey.OFFICE, new TagValue[] {
                INSURANCE,
                NEWSPAPER,
                ADOPTION_AGENCY,
                EDUCATIONAL_INSTITUTION,
                ACCOUNTANT,
                ENERGY_SUPPLIER,
                TAX_ADVISOR,
                ARCHITECT,
                ASSOCIATION,
                RESEARCH,
                POLITICAL_PARTY,
                DIPLOMATIC,
                GOVERNMENT,
                CHARITY,
                GEODESIST,
                PARISH,
                NGO,
                ADVERTISING_AGENCY,
                ESTATE_AGENT,
                GUIDE,
                LAWYER,
                THERAPIST,
                EMPLOYMENT_AGENCY,
                SURVEYOR,
                RELIGION,
                MOVING_COMPANY,
                TRAVEL_AGENT,
                ADMINISTRATIVE,
                FORESTRY
        });
        defineKnownValues(TagKey.FORD, new TagValue[] {
                STEPPING_STONES,
                YES
        });
        defineKnownValues(TagKey.OPERATOR, new TagValue[] {
                CAMBIO,
                STADTMOBIL,
                CAMBIO,
                BOOK_N_DRIVE,
                TEILAUTO,
                STADTMOBIL,
                CITEECAR,
                FLINKSTER,
                DRIVE_CARSHARING
        });
        defineKnownValues(TagKey.BUSWAY, new TagValue[] {
                LANE
        });
        defineKnownValues(TagKey.BARRIER, new TagValue[] {
                SALLY_PORT,
                DITCH,
                KISSING_GATE,
                STILE,
                GUARD_RAIL,
                LIFT_GATE,
                HEDGE,
                RETAINING_WALL,
                CITY_WALL,
                TURNSTILE,
                BOLLARD,
                FULL_HEIGHT_TURNSTILE,
                HEDGE_BANK,
                HEIGHT_RESTRICTOR,
                BLOCK,
                TOLL_BOOTH,
                CATTLE_GRID,
                GATE,
                ENTRANCE,
                CYCLE_BARRIER,
                FENCE,
                WALL
        });
        defineKnownValues(TagKey.LIT, new TagValue[] {
                NO,
                YES,
                AUTOMATIC
        });
        defineKnownValues(TagKey.SUBSTATION, new TagValue[] {
                TRANSMISSION,
                CONVERTER,
                TRACTION,
                MINOR_DISTRIBUTION,
                DISTRIBUTION
        });
        defineKnownValues(TagKey.CLUB, new TagValue[] {
                AUTOMOBILE,
                FAN,
                SCOUT,
                SPORT
        });
        defineKnownValues(TagKey.MILITARY, new TagValue[] {
                BUNKER,
                BARRACKS,
                NAVAL_BASE,
                NUCLEAR_EXPLOSION_SITE,
                AIRFIELD,
                DANGER_AREA,
                RANGE,
                TRAINING_AREA
        });
        defineKnownValues(TagKey.ATM, new TagValue[] {
                YES
        });
        defineKnownValues(TagKey.HIGHWAY, new TagValue[] {
                DOOR,
                CORRIDOR,
                PRIMARY_LINK,
                RURAL,
                REST_AREA,
                PATH,
                ELEVATOR,
                ROAD,
                ABANDONED,
                STREET_LAMP,
                TERTIARY_LINK,
                BYWAY,
                TERTIARY,
                SPEED_CAMERA,
                LIVING_STREET,
                MOTORWAY_LINK,
                TRUNK,
                CROSSING,
                MOTORWAY,
                STEPS,
                RESIDENTIAL_UNCLASSIFIED,
                SECONDARY,
                PASSING_PLACE,
                MOTORWAY_JUNCTION,
                PROPOSED,
                STOP,
                TURNING_CIRCLE,
                KERB,
                FOOTWAY,
                EMERGENCY_BAY,
                CYCLEWAY,
                TRUNK_LINK,
                PRIMARY,
                NO,
                UNCLASSIFIED,
                ACCESS,
                TURNING_LOOP,
                TRUNK_JUNCTION,
                TRAFFIC_SIGN,
                BUS_GUIDEWAY,
                PLANNED,
                PLATFORM,
                UNKNOWN,
                RACEWAY,
                STREET_LIGHT,
                TRAFFIC_SIGNALS,
                CONSTRUCTION,
                SECONDARY_LINK,
                TRACK,
                TRAFFIC_MIRROR,
                ESCAPE,
                GIVE_WAY,
                NOEXIT,
                EMERGENCY_ACCESS_POINT,
                BRIDLEWAY,
                YES,
                MINI_ROUNDABOUT,
                SERVICES,
                DISUSED,
                RESIDENTIAL,
                MILESTONE,
                SERVICE,
                PEDESTRIAN,
                BUS_STOP,
                RAZED
        });
        defineKnownValues(TagKey.ENTRANCE, new TagValue[] {
                YES,
                MAIN,
                STAIRCASE
        });
        defineKnownValues(TagKey.WETLAND, new TagValue[] {
                REEDBED,
                SALTERN,
                WET_MEADOW,
                TIDALFLAT,
                BOG,
                MANGROVE,
                SWAMP,
                MUD,
                SALTMARSH,
                STRING_BOG,
                FEN,
                MARSH
        });
        defineKnownValues(TagKey.VENDING, new TagValue[] {
                BOTTLE_RETURN,
                BREAD,
                FLOWERS,
                PARCEL_PICKUP_PARCEL_MAIL_IN,
                TOYS,
                ELONGATED_COIN,
                MILK,
                BICYCLE_TUBE,
                CANDLES,
                NEWSPAPERS,
                WATER,
                FOOD,
                ICE_CREAM,
                CHEWING_GUMS,
                PARCEL_PICKUP,
                COFFEE,
                PARKING_TICKETS,
                ANIMAL_FEED,
                EXCREMENT_BAGS,
                PUBLIC_TRANSPORT_TICKETS,
                PARCEL_MAIL_IN,
                SEX_TOYS,
                STAMPS
        });
        defineKnownValues(TagKey.WATER, new TagValue[] {
                POND,
                WASTEWATER,
                OXBOW,
                LOCK,
                CANAL,
                RESERVOIR,
                RIVER,
                LAKE,
                LAGOON
        });
        defineKnownValues(TagKey.LEVEL_CROSSING, new TagValue[] {
                AUTOMATIC_BARRIER,
                TRAFFIC_SIGNALS,
                UNCONTROLLED
        });
        defineKnownValues(TagKey.MUSEUM, new TagValue[] {
                CHILDREN,
                NATURE,
                OPEN_AIR,
                HISTORY,
                RAILWAY,
                LOCAL
        });
        defineKnownValues(TagKey.FOOTWAY, new TagValue[] {
                SIDEWALK,
                CROSSING
        });
        defineKnownValues(TagKey.CYCLEWAY, new TagValue[] {
                OPPOSITE_TRACK,
                SHARE_BUSWAY,
                OPPOSITE_LANE,
                OPPOSITE,
                TRACK,
                LANE
        });
        defineKnownValues(TagKey.BOUNDARY, new TagValue[] {
                ADMINISTRATIVE,
                NATIONAL_PARK,
                PROTECTED_AREA,
                RELIGIOUS_ADMINISTRATION,
                POSTAL_CODE,
                WATER_PROTECTION_AREA
        });
        defineKnownValues(TagKey.SHOP, new TagValue[] {
                GIFT,
                ELECTRONICS,
                EQUESTRIAN,
                BICYCLE,
                TRAVEL_AGENCY,
                VARIETY_STORE,
                BAG,
                PAINT,
                WIGS,
                CONVENIENCE,
                CAR_REPAIR,
                COPYSHOP,
                ICE_CREAM,
                CHEESE,
                LOCKSMITH,
                ROBOT,
                TEA,
                TILES,
                MUSIC,
                GREENGROCER,
                VIDEO_GAMES,
                FARM,
                ANTIQUES,
                MODEL,
                NEWSAGENT,
                BATHROOM_FURNISHING,
                HUNTING,
                PET,
                SWIMMING_POOL,
                HARDWARE,
                ALCOHOL,
                BEVERAGES,
                SPARE_PARTS,
                BAKERY,
                BOUTIQUE,
                MALL,
                LEATHER,
                VACANT,
                HOUSEWARE,
                TATTOO,
                BOOKS,
                FABRIC,
                EROTIC,
                WEAPONS,
                WINE,
                CHOCOLATE,
                PAWNBROKER,
                WINDOW_BLIND,
                DEPARTMENT_STORE,
                HAIRDRESSER_SUPPLY,
                TAILOR,
                SCUBA_DIVING,
                FIREPLACE,
                SUPERMARKET,
                COMPUTER,
                GOLF,
                HAIRDRESSER,
                WHOLESALE,
                LAUNDRY,
                GARDEN_CENTRE,
                FROZEN_FOOD,
                SEWING,
                CAMERA,
                HERBALIST,
                KITCHEN,
                TROPHY,
                SEAFOOD,
                TYRES,
                CERAMICS,
                ART,
                HEALTH_FOOD,
                PHOTO,
                OPTICIAN,
                SHOES,
                RELIGION,
                PASTRY,
                PERFUMERY,
                CAR_PARTS,
                DRY_CLEANING,
                DAIRY,
                FASHION,
                BED,
                WOOL,
                BEAUTY,
                LAMPS,
                CRAFT,
                BUTCHER,
                DELI,
                MOTORCYCLE,
                CHARITY,
                FURNITURE,
                SECOND_HAND,
                BOOKMAKER,
                FLORIST,
                FUNERAL_DIRECTORS,
                STATIONERY,
                TOBACCO,
                MASSAGE,
                JEWELRY,
                BABY_GOODS,
                WATCHES,
                ATV,
                INTERIOR_DECORATION,
                MEDICAL_SUPPLY,
                STORAGE_RENTAL,
                HIFI,
                CARPET,
                SPICES,
                CURTAIN,
                PARTY,
                FRAME,
                APPLIANCE,
                FLOORING,
                HEARING_AIDS,
                CANDLES,
                CONFECTIONERY,
                VIDEO,
                COLLECTOR,
                COSMETICS,
                GENERAL,
                HABERDASHERY,
                CAR,
                MOBILE_PHONE,
                GAS,
                MUSICAL_INSTRUMENT,
                CHEMIST,
                DOITYOURSELF,
                TOYS,
                SPORTS,
                TICKET,
                FISHING,
                CLOTHES,
                OUTDOOR,
                AGRARIAN,
                POTTERY,
                TRADE,
                COFFEE,
                KIOSK
        });
        defineKnownValues(TagKey.ABANDONED_AMENITY, new TagValue[] {
                PRISON_CAMP,
                PRISON
        });
        defineKnownValues(TagKey.LINE, new TagValue[] {
                BUSBAR,
                BAY
        });
        defineKnownValues(TagKey.MOTORCAR, new TagValue[] {
                NO
        });
        defineKnownValues(TagKey.FORTIFICATION_TYPE, new TagValue[] {
                SCONCE,
                HILL_FORT,
                LIMES,
                RINGFORT
        });
        defineKnownValues(TagKey.ARTWORK_TYPE, new TagValue[] {
                STATUE,
                SCULPTURE
        });
        defineKnownValues(TagKey.NETWORK, new TagValue[] {
                IWN,
                LWN,
                NWN,
                RWN,
                CAMBIO_STADTMOBIL,
                LHN,
                CALL_A_BIKE,
                ICN,
                LCN,
                NCN,
                NEXTBIKE,
                RHN,
                FLINKSTER,
                RCN
        });
        defineKnownValues(TagKey.MOTOR_VEHICLE, new TagValue[] {
                DESTINATION
        });
        defineKnownValues(TagKey.CASTLE_TYPE, new TagValue[] {
                MANOR,
                PALACE,
                CASTRUM,
                FORTRESS,
                STATELY,
                DEFENSIVE
        });
        defineKnownValues(TagKey.STATION, new TagValue[] {
                SUBWAY,
                LIGHT_RAIL
        });
        defineKnownValues(TagKey.CONSTRUCTION, new TagValue[] {
                UNCLASSIFIED,
                MINOR,
                PRIMARY_LINK,
                LIGHT_RAIL,
                MONORAIL,
                PRESERVED,
                TRACK,
                TRAM,
                NARROW_GAUGE,
                BRIDLEWAY,
                RAIL,
                TERTIARY,
                MOTORWAY_LINK,
                TRUNK,
                MOTORWAY,
                STEPS,
                SECONDARY,
                RESIDENTIAL,
                SUBWAY,
                SERVICE,
                FOOTWAY,
                PEDESTRIAN,
                CYCLEWAY,
                TRUNK_LINK,
                PRIMARY
        });
        defineKnownValues(TagKey.ZOO, new TagValue[] {
                SAFARI_PARK,
                AVIARY,
                ENCLOSURE,
                BUTTERFLY,
                PETTING_ZOO,
                REPTILE,
                BIRDS,
                WILDLIFE_PARK,
                FALCONRY
        });
        defineKnownValues(TagKey.MEMORIAL, new TagValue[] {
                PLAQUE,
                OBELISK,
                STELE,
                STATUE,
                BUST,
                STOLPERSTEIN,
                STONE,
                WAR_MEMORIAL
        });
        defineKnownValues(TagKey.HISTORIC, new TagValue[] {
                ARCHAEOLOGICAL_SITE,
                BOMB_CRATER,
                CASTLE,
                CITYWALLS,
                CHARCOAL_PILE,
                SHIP,
                MONUMENT,
                BUILDING,
                MANOR,
                WRECK,
                CITY_GATE,
                PILLORY,
                LOCOMOTIVE,
                BOUNDARY_STONE,
                RUNE_STONE,
                OPTICAL_TELEGRAPH,
                MEMORIAL,
                MINE,
                WAYSIDE_SHRINE,
                TOMB,
                AIRCRAFT,
                WAYSIDE_CROSS,
                STONE,
                MONASTERY,
                MILESTONE,
                BATTLEFIELD,
                RUINS,
                FORT,
                GALLOWS
        });
        defineKnownValues(TagKey.INTERNET_ACCESS, new TagValue[] {
                WLAN
        });
        defineKnownValues(TagKey.MAN_MADE, new TagValue[] {
                ANTENNA,
                DYKE,
                BREAKWATER,
                GOODS_CONVEYOR,
                WATER_WORKS,
                MONITORING_STATION,
                INSECT_HOTEL,
                MDF,
                EMBANKMENT,
                FLAGPOLE,
                CELLAR_ENTRANCE,
                WATER_WELL,
                TOWER,
                SPOIL_HEAP,
                CRANE,
                ADIT,
                WINDMILL,
                PETROLEUM_WELL,
                BUNKER_SILO,
                GROYNE,
                BEACON,
                DOVECOTE,
                SNOW_CANNON,
                RESERVOIR_COVERED,
                WATER_TAP,
                BRIDGE,
                COOLING_TOWER,
                OFFSHORE_PLATFORM,
                TELESCOPE,
                COMMUNICATIONS_TOWER,
                CHIMNEY,
                WORKS,
                LIGHTHOUSE,
                MAST,
                POWER_WIND,
                MINESHAFT,
                BEEHIVE,
                NESTING_SITE,
                OBSERVATORY,
                STORAGE_TANK,
                KILN,
                PIER,
                PUMPING_STATION,
                SATELLITE_DISH,
                WATER_TOWER,
                WILDLIFE_CROSSING,
                OBELISK,
                SURVEILLANCE,
                SURVEY_POINT,
                CROSS,
                WASTEWATER_PLANT,
                HOT_WATER_TANK,
                SILO,
                PIPELINE,
                CUTLINE,
                GASOMETER,
                WATERMILL,
                MAYPOLE,
                WATER_TANK
        });
        defineKnownValues(TagKey.BIOSPHÄRENWIRT, new TagValue[] {
                YES
        });
        defineKnownValues(TagKey.WATERWAY, new TagValue[] {
                WEIR,
                DERELICT_CANAL,
                DITCH,
                FUEL,
                RIVERBANK,
                FISH_PASS,
                DRAIN,
                DAM,
                BOATYARD,
                LOCK_GATE,
                MILESTONE,
                STREAM,
                WATERFALL,
                BOAT_LIFT,
                CANAL,
                RIVER,
                DOCK,
                PRESSURISED
        });
        defineKnownValues(TagKey.CUISINE, new TagValue[] {
                COFFEE_SHOP
        });
        defineKnownValues(TagKey.DISUSED, new TagValue[] {
                YES
        });
        defineKnownValues(TagKey.INDUSTRIAL, new TagValue[] {
                SCRAP_YARD,
                BAKERY
        });
        defineKnownValues(TagKey.ATTRACTION, new TagValue[] {
                SUMMER_TOBOGGAN,
                ANIMAL,
                WATER_SLIDE,
                TRAIN
        });
        defineKnownValues(TagKey.AIRMARK, new TagValue[] {
                BEACON
        });
        defineKnownValues(TagKey.SERVICE, new TagValue[] {
                SIDING,
                CROSSOVER,
                DRIVEWAY,
                YARD,
                EMERGENCY_ACCESS,
                AIRCRAFT_CONTROL,
                PARKING_AISLE,
                ALLEY,
                SPUR
        });
        defineKnownValues(TagKey.MEGALITH_TYPE, new TagValue[] {
                LONG_BARROW,
                PASSAGE_GRAVE,
                CHAMBER,
                DOLMEN,
                NURAGHE,
                MENHIR,
                CIST,
                THOLOS,
                STONE_CIRCLE,
                ALIGNMENT,
                STONE_SHIP
        });
        defineKnownValues(TagKey.SPORT, new TagValue[] {
                MOTOR,
                EQUESTRIAN,
                SKATEBOARD,
                BOBSLEIGH,
                SHOOTING,
                SCUBA_DIVING,
                TABLE_SOCCER,
                BMX,
                MULTI,
                FREE_FLYING,
                ICE_SKATING,
                RUNNING,
                SWIMMING,
                BASKETBALL,
                GOLF,
                TRAMPOLINE,
                _10PIN,
                CLIMBING,
                SOCCER,
                CHESS,
                _9PIN,
                JUDO,
                MOTOCROSS,
                BADMINTON,
                CLIMBING_ADVENTURE,
                HORSE_RACING,
                RC_CAR,
                TENNIS,
                TABLE_TENNIS,
                AMERICAN_FOOTBALL,
                HANDBALL,
                TOBOGGAN,
                KARTING,
                BOXING,
                BASEBALL,
                VOLLEYBALL,
                ATHLETICS,
                SAILING,
                ARCHERY,
                FENCING
        });
        defineKnownValues(TagKey.TUNNEL, new TagValue[] {
                CULVERT,
                BUILDING_PASSAGE,
                YES
        });
        defineKnownValues(TagKey.AEROWAY, new TagValue[] {
                HANGAR,
                APRON,
                RUNWAY,
                WINDSOCK,
                TERMINAL,
                HELIPORT,
                TAXILANE,
                HOLDING_POSITION,
                PARKING_POSITION,
                AERODROME,
                TAXIWAY,
                SPACEPORT,
                NAVIGATIONAID,
                GATE,
                HELIPAD
        });

    }

    private void defineKnownValues(TagKey tagKey, TagValue[] values) {
        Set<TagValue> valueSet = new HashSet<>(values.length);
        valueSet.addAll(Arrays.asList(values));
        put(tagKey, valueSet);
    }
}
